const multiLanguage = {
    'ko': {
        friend: '친구',
        chatRoom: '채팅방',
        searchUser: '사용자명#0000',
        alreadyFriend: '이미 친구로 등록된 사용자예요!',
        invalidUser: '이름과 태그가 정확한지 다시 한 번 확인해주세요.',
        myAccount: '내 계정',
        justEmail: '이메일',
        langSetting: '언어 설정',
        deleteAccount: '계정 삭제',
        deleteAccountSure: '정말 계정을 삭제하시겠어요? 삭제 후에는 되돌릴 수 없어요.',
        logout: '로그아웃',
        logoutSure: '현재 계정에서 로그아웃하시겠어요?',
        createRoom: '채팅방 만들기',
        createNewRoom: '새 채팅방 개설하기',
        orJoin: '또는 참가하기',
        inviteCode: '입장 코드',
        inputInviteCode: '입장 코드를 입력하세요.',
        invalidInviteCode: '입장 코드 - 유효한 입장 코드를 입력하세요',
        join: '참가하기',
        settingRoom: '채팅방 설정',
        roomName: '채팅방 이름',
        inputRoomName: '채팅방 이름을 적어주세요.',
        create: '만들기',
        back: '돌아가기',
        inviteFriend: '친구 초대하기',
        sendCode: '친구에게 입장 코드를 전송하세요!',
        copy: '복사',
        copyComplete: '복사 완료!',
        exitRoom: '채팅방 나가기',
        exitRoomSure: '재입장하려면 다시 초대를 받아야 합니다. 정말 나가시겠어요?',
        exit: '나가기',
        cancle: '취소',
        delete: '삭제',
        accessDenied: '접속 불가',
        doNotHavePermission: '접근 권한이 없습니다.',
        logsNothing: '대화 기록이 없어요.',
        stranger: '아직 친구로 등록되지 않은 사용자에요.',
        register: '등록',
        loading: '번역 중...'
    },
    'en': {
        friend: 'Friend',
        chatRoom: 'Chat room',
        searchUser: 'Username#0000',
        alreadyFriend: 'You are already registered as a friend!',
        invalidUser: 'Please check again if the name and tag are correct.',
        myAccount: 'My Account',
        justEmail: 'Email',
        langSetting: 'Language Setting',
        deleteAccount: 'Delete Account',
        deleteAccountSure: 'Are you sure you want to delete the account?',
        logout: 'Logout',
        logoutSure: 'Do you want to log out of your current account?',
        createRoom: 'Create a chat room',
        createNewRoom: 'Create a new chat room',
        orJoin: 'or Join',
        inviteCode: 'Entry Code',
        inputInviteCode: 'Please enter the Entry code.',
        invalidInviteCode: 'Invitation Code - Please enter the Entry code.',
        join: 'Join',
        settingRoom: 'Chat room settings',
        roomName: 'Chat room name',
        inputRoomName: 'Please write down the name of the chat room.',
        create: 'Create',
        back: 'Back',
        inviteFriend: 'Invite a Friend',
        sendCode: 'Send your entry code to your friend!',
        copy: 'Copy',
        copyComplete: 'Copy complete!',
        exitRoom: 'Leave the chat room.',
        exitRoomSure: 'You must be invited back to re-enter.<br>Are you sure you want to go out?',
        exit: 'Leave',
        cancle: 'Cancle',
        delete: 'Delete',
        accessDenied: 'Access Denied',
        doNotHavePermission: 'You do not have access.',
        logsNothing: 'No conversation logs available.',
        stranger: 'User is not registered as a friend yet.',
        register: 'Register',
        loading: 'Loading...'
    },
    'ja': {
        friend: '友達',
        chatRoom: 'チャットルーム',
        searchUser: 'ユーザー名#0000',
        alreadyFriend: '既に友達登録されているユーザーです！',
        invalidUser: '名前とタグが正しいかもう一度確認してください。',
        myAccount: 'マイアカウント',
        justEmail: 'メール',
        langSetting: '言語設定',
        deleteAccount: 'アカウント削除',
        deleteAccountSure: '本当にアカウントを削除しますか？<br>削除後は元に戻せません。',
        logout: 'ログアウト',
        logoutSure: '現在のアカウントからログアウトしますか？',
        createRoom: 'チャットルーム作成',
        createNewRoom: '新しいチャットルームを作成する',
        orJoin: 'または参加する',
        inviteCode: '招待コード',
        inputInviteCode: '招待コードを入力してください。',
        invalidInviteCode: '招待コード-有効な招待コードを入力してください',
        join: '参加する',
        settingRoom: 'チャットルーム設定',
        roomName: 'チャットルーム名',
        inputRoomName: 'チャットルーム名を入力してください。',
        create: '作成する',
        back: '戻る',
        inviteFriend: '友達を招待する',
        sendCode: '友達に入場コードを送信してください！',
        copy: 'コピー',
        copyComplete: 'コピーが完了しました！',
        exitRoom: 'チャットルームを退出する',
        exitRoomSure: '再入場するには、再度招待を受ける必要があります。<br>本当に退出しますか？',
        exit: '退出する',
        cancle: 'キャンセル',
        delete: '削除する',
        accessDenied: '接続不可',
        doNotHavePermission: 'アクセス権がありません。',
        logsNothing: '会話ログがありません。',
        stranger: 'まだ友達登録されていないユーザーです。',
        register: '登録',
        loading: '翻訳中...'
    },
    'zh-CN': {
        friend: '朋友',
        chatRoom: '聊天室',
        searchUser: '使用者名稱#0000',
        alreadyFriend: '該使用者已是您的好友！',
        invalidUser: '請確認名稱和標籤是否正確。',
        myAccount: '我的帳戶',
        justEmail: '電子郵件',
        langSetting: '語言設置',
        deleteAccount: '刪除帳戶',
        deleteAccountSure: '您確定要刪除帳戶嗎？<br>刪除後無法恢復。',
        logout: '登出',
        logoutSure: '您確定要從當前帳戶登出嗎？',
        createRoom: '創建聊天室',
        createNewRoom: '創建新聊天室',
        orJoin: '或者加入',
        inviteCode: '入場代碼',
        inputInviteCode: '請輸入入場碼。',
        invalidInviteCode: '入場碼-請輸入有效的入場碼',
        join: '加入',
        settingRoom: '聊天室設置',
        roomName: '聊天室名稱',
        inputRoomName: '請輸入聊天室名稱。',
        create: '創建',
        back: '返回',
        inviteFriend: '邀請好友',
        sendCode: '向好友發送入場碼！',
        copy: '複製',
        copyComplete: '已複製！',
        exitRoom: '退出聊天室',
        exitRoomSure: '您確定要退出聊天室嗎？<br>您需要重新獲取邀請碼以重新進入。',
        exit: '退出',
        cancle: '取消',
        delete: '刪除',
        accessDenied: '無法連接',
        doNotHavePermission: '您沒有訪問權限。',
        logsNothing: '沒有對話記錄。',
        stranger: '用戶尚未註冊為好友。',
        register: '註冊',
        loading: '翻譯中...'
    },
    'zh-TW': {
        friend: '朋友',
        chatRoom: '聊天室',
        searchUser: '用户名#0000',
        alreadyFriend: '该用户已是您的好友！',
        invalidUser: '请确认名称和标签是否正确。',
        myAccount: '我的帐户',
        justEmail: '电子邮件',
        langSetting: '语言设置',
        deleteAccount: '删除账户',
        deleteAccountSure: '您确定要删除账户吗？<br>删除后无法恢复。',
        logout: '退出登录',
        logoutSure: '您确定要从当前账户退出登录吗？',
        createRoom: '创建聊天室',
        createNewRoom: '创建新聊天室',
        orJoin: '或者加入',
        inviteCode: '入场代码',
        inputInviteCode: '请输入入场码。',
        invalidInviteCode: '入场码-请输入有效的入场码',
        join: '加入',
        settingRoom: '聊天室设置',
        roomName: '聊天室名称',
        inputRoomName: '请输入聊天室名称。',
        create: '创建',
        back: '返回',
        inviteFriend: '邀请好友',
        sendCode: '向好友发送入场码！',
        copy: '复制',
        copyComplete: '已复制！',
        exitRoom: '退出聊天室',
        exitRoomSure: '您确定要退出聊天室吗？<br>您需要重新获取邀请码以重新进入。',
        exit: '退出',
        cancel: '取消',
        delete: '删除',
        accessDenied: '无法连接',
        doNotHavePermission: '您没有访问权限。',
        logsNothing: '没有对话记录。',
        stranger: '用户尚未注册为好友。',
        register: '注册',
        loading: '翻译中...'
    }
}

function setLanguage(lang) {
    let changeNodeList = Array.prototype.slice.call(document.querySelectorAll('[data-detect]'));
    changeNodeList.map(v => {
        v.innerHTML = multiLanguage[lang][v.dataset.detect]
    });
}